name: Manual Workflow
run-name: ${{ github.actor }} is testing manual GitHub Actions
on: [workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2022.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Create new acf project and push it to github
        run: |
          plcncli new acfproject
          git config user.email "martin.boers@gmail.com"
          git config --global user.name "Martin Boers"
          git add --all --verbose
          git -c user.name=$name -c user.email=$email commit -am "Create project from template"
          git push
