name: Manual Workflow
run-name: ${{ github.actor }} is testing manual GitHub Actions
on: [workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2022.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Create new acf project and push it to github
        run: |
          plcncli new acfproject
          git config user.email user.email=$email
          git config user.name user.name=$name
          git add --all --verbose
          git commit -am "Create project from template"
          git push
