name: Build Project
run-name: ${{ github.actor }} is building the project
on: [workflow_dispatch]
jobs:
  project-build-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2022.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build project
        run: |
          plcncli --version
          plcncli set target --name AXCF2152 --version 2022.6 --add
          plcncli generate code
          plcncli build --buildtype Release
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin
