name: Create ACF Project
run-name: ${{ github.actor }} is creating a new ACF project
on: [workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: martinboers/plcnext-build-environment:axcf2152-2022.6
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Create new acf project and push it to github
        run: |
          plcncli new acfproject
          rm .github/workflows/create-acf-project.yml
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add --all --verbose
          git commit -m "Create project from template"
          git push
